# Generated by Django 2.2.7 on 2019-11-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191105_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
